kk<?php
set_time_limit(0);
error_reporting(0);
$list['front'] ="admin
adm
admincp
admcp
cp
modcp
moderatorcp
adminarea
admins
cpanel
controlpanel";
$list['end'] = "admin1.php
admin1.html
admin2.php
adminweb/
adminweb/index.php
redaktur/index.php
v2/login/
v2/adminweb/
v2/4dm1n15tr4t0r/
v2/adminpn/
v2/adminpa/
v2/adminpanel/
web/administrator/
web/4dm1n/
CHANGELOG.txt
panel/kcfinder/upload.php
admin/assest/kcfinder/
symlink.php
assets/server/php
elfinder/
assets/elfinder/php/connector/
assets/
timthumb.php
adminback/
alhamdulillah/
entry/
enter/
aturdata/
menu/login/
buffffg/
yaambon/
pemkab/
pemkabadmin/
restric/
po-admin/
cms/index.php
kantor/admin_login.php
kantor/4dm1n.php
kantor/loginadmin.php
kantor/user.php
index.php/login
adminarea
admin2.html
yonetim.php
yonetim.html
yonetici.php
yonetici.html
ccms/
panitia/
datinfo/
posko/
infologin/
adminpa/
4dm1np4/
4dm1n15tr4t0rpa/
l0g1np4/
p4/
adminpn/
loginpn/
v2/admin/
login@web/
loginweb/
konten/
dinas/
akademik/
templates/
simaset/
elearningku/proses.php
ccms/login.php
user/login.php
ccms/index.php
maintenance/
webmaster/
adm/
config/
configuration/
kontenweb/
configure/
websvn/
ketua/
panitia/
loginpanitia/
pemerintah/
adminrs
rsadminulin
adminulinrs
@4m!N!$trAt0r/
cybercrime/
adipura/
pintumasuk/
pintu/
blusukan/
tersembunyi/
bapeda/
loggin/
admin/
admin.php
admin.html
admin/cp.php
login/adminpa/
login/adminpn/
login/pn/
login/pa/
admin/cp.html
cp.php
no7.php
uploader.phtml
alfa.php
x.php
asw.php
bar.php
xnxx.php
bar.php
404.php
shell.php
dotlogin/
dotlogin1/
cp.html
siakad/
journal/
sia/
fakultas/
pegawai/
petugas/
penjaga/
4dminW3B/
adminhotel/
config/
akademik/
admin2017/
admin2016/
2016/
intranet/
2017/
admin2015/
indonesia/
garuda/
g4rud4/
kelolaweb/
aturweb/
counter/
bpadmin/
suradmin/
basecamp/
padmin/
pengaturan/
setting/
settingweb/
redaksi/
adminweb1/
redaktur1/
masukweb/
lokoadmin/
lokoadministrator/
lokoadminweb/
lokoredaksiweb/
redaksiweb/
users/
usr/
user/
back/
loginuser/
logincms/
backupadmin/
backup/
b4ckup/
adminhost/
admincms/
userlogin/
adminkampus/
redaksiweb/adweb/
bismillah/
adweb2_cad/
kuncen/
dasboard/
administrator/
administrator.php
administrator.html
login.php
login.html
modelsearch/login.php
moderator.php
moderator.html
moderator/
moderator/login.html
moderator/admin.php
moderator/admin.html
moderator/
account.php
account.html
controlpanel/
controlpanel.php
controlpanel.html
admincontrol.php
admincontrol.html
adminpanel.php
adminpanel.html
admin1.asp
admin2.asp
yonetim.asp
yonetici.asp
admin/account.asp
admin/index.asp
admin/login.asp
admin/home.asp
admin/controlpanel.asp
admin.asp
admin/cp.asp
cp.asp
administrator/index.asp
administrator/login.asp
administrator/account.asp
administrator.asp
login.asp
modelsearch/login.asp
moderator.asp
moderator/login.asp
moderator/admin.asp
account.asp
controlpanel.asp
admincontrol.asp
adminpanel.asp
fileadmin/
fileadmin.php
fileadmin.asp
fileadmin.html
administration/
administration.php
administration.html
sysadmin.php
sysadmin.html
phpmyadmin/
myadmin/
sysadmin.asp
sysadmin/
ur-admin.asp
ur-admin.php
ur-admin.html
ur-admin/
Server.php
Server.html
Server.asp
Server/
wp-admin/
administr8.php
administr8.html
administr8/
administr8.asp
webadmin/
webadmin.php
webadmin.asp
webadmin.html
administratie/
admins/
admins.php
admins.asp
admins.html
administrivia/
Database_Administration/
WebAdmin/
useradmin/
sysadmins/
admin1/
system-administration/
administrators/
bugmkx/
kembug/
pgadmin/
welcome/admin/
directadmin/
staradmin/
ServerAdministrator/
SysAdmin/
administer/
LiveUser_Admin/
sys-admin/
typo3/
panel/
cpanel/
cPanel/
cpanel_file/
platz_login/
rcLogin/
blogindex/
formslogin/
autologin/
support_login/
meta_login/
manuallogin/
simpleLogin/
loginflat/
utility_login/
showlogin/
memlogin/
members/
login-redirect/
sub-login/
wp-login/
login1/
dir-login/
login_db/
xlogin/
smblogin/
customer_login/
UserLogin/
login-us/
acct_login/
admin_area/
bigadmin/
project-admins/
phppgadmin/
pureadmin/
sql-admin/
radmind/
openvpnadmin/
wizmysqladmin/
vadmind/
ezsqliteadmin/
hpwebjetadmin/
newsadmin/
adminpro/
Lotus_Domino_Admin/
bbadmin/
vmailadmin/
Indy_admin/
ccp14admin/
irc-macadmin/
banneradmin/
sshadmin/
phpldapadmin/
macadmin/
administratoraccounts/
admin4_account/
admin4_colon/
radmind-1/
Super-Admin/
AdminTools/
cmsadmin/
SysAdmin2/
globes_admin/
cadmins/
phpSQLiteAdmin/
navSiteAdmin/
server_admin_small/
logo_sysadmin/
server/
database_administration/
power_user/
system_administration/
ss_vms_admin_sm/
adminarea/
bb-admin/
adminLogin/
panel-administracion/
instadmin/
memberadmin/
administratorlogin/
admin/admin.php
admin_area/admin.php
admin_area/
siteadmin/login.php
siteadmin/index.php
siteadmin/login.html
admin/admin.html
admin_area/index.php
bb-admin/index.php
bb-admin/login.php
bb-admin/admin.php
admin_area/login.html
admin_area/index.html
admincp/index.asp
admincp/login.asp
admincp/index.html
webadmin/index.html
webadmin/admin.html
webadmin/login.html
admin/admin_login.html
admin_login.html
panel-administracion/login.html
nsw/admin/login.php
webadmin/login.php
admin/admin_login.php
admin_login.php
admin_area/admin.html
pages/admin/admin-login.php
admin/admin-login.php
admin-login.php
adsite/
adsite/login.php
bb-admin/index.html
bb-admin/login.html
bb-admin/admin.html
admin/home.html
pages/admin/admin-login.html
admin/admin-login.html
admin-login.html
admin/adminLogin.html
adminLogin.html
home.html
rcjakar/admin/login.php
adminarea/index.html
adminarea/admin.html
webadmin/index.php
webadmin/admin.php
user.html
modelsearch/login.html
adminarea/login.html
panel-administracion/index.html
panel-administracion/admin.html
modelsearch/index.html
modelsearch/admin.html
admincontrol/login.html
adm/index.html
back/login.html
adm.html
user.php
panel-administracion/login.php
wp-login.php
adminLogin.php
admin/adminLogin.php
home.php
adminarea/index.php
adminarea/admin.php
adminarea/login.php
panel-administracion/index.php
panel-administracion/admin.php
modelsearch/index.php
modelsearch/admin.php
admincontrol/login.php
adm/admloginuser.php
admloginuser.php
admin2/login.php
admin2/index.php
adm/index.php
adm.php
affiliate.php
adm_auth.php
memberadmin.php
administratorlogin.php
admin/admin.asp
admin_area/admin.asp
admin_area/login.asp
admin_area/index.asp
bb-admin/index.asp
bb-admin/login.asp
bb-admin/admin.asp
pages/admin/admin-login.asp
admin/index.php
admin/login.php
back/login.php
nimda
adminpmb
panel
akreditasi
staff
member
adminare
admins
redakturweb/
login@web/
adminpanel/
usuarios/
usuario/
adminarea/
bb-admin/
adminLogin/
retel/
operator/
adm/
_adm_/
timadmin/
teamadmin/
myadmin/
masuk/
adminkel/
4dm1n/
loggon/
adminpa/
admindisbun/
_admin_/
loginadm
login_admin/
_loginadmin_/
login_admin.php
_admin_/
_administrator_/
operator/
sika/
develop/
ketua/
redaktur/
author/
master/4dmin/
dinkesadmin/
paneladmin/
panellogin/
Login@web/
master/
master/index.php
master/login.php
operator/index.php
wp-login.php?action=register
sika/index.php
develop/index.php
ketua/index.php
redaktur/index.php
wp-admin/install.php
user/index.php
users/index.php
dinkesadmin/index.php
retel/index.php
author/index.php
panel/index.php
paneladmin/index.php
panenellogin/index.php
redaksi/index.php
terasadmin/
terasadmin/index.php
terasadmin/login.php
rahasia/
rahasia/index.php
rahasia/admin.php
rahasia/login.php
dinkesadmin/
dinkesadmin/login.php
adminpmb/
kantor/admin_login.php
kantor/login.php
kantor/4dm1n/
adminpmb/index.php
adminpmb/login.php
system/
system/index.php
system/login.php
webadmin/index.php
webadmin/login.php
wpanel/
wpanel/index.php
wpanel/login.php
adminpanel/index.php
adminpanel/
adminpanel/login.phh
adminkec/
adminkec/index.php
adminkec/login.php
admindesa/
admindesa/index.php
admindesa/login.php
adminkota/
ladminkota/index.php
adminkota/login.php
admin123/
admin123/index.php
dologin/
home.asp/
supervise/amdin
relogin/adm
checkuser
relogin.php
relogin.asp
registration
suvervise
tinymcpuk/
bpkad/
foto_user/
files/
paneladmin/
panellogin/
admin/modules/bibliography/pop_attach.php
retel/
tinymcpuk/filemanager/
kcfinder/browser.php
adminpanel/ckeditor/kcfinder/browse.php
assest/kcfinder/upload.php
kcfinder/upload.php
admins/
sika/
assest/
develop/
Admin/
lobangdotid/
dinkesadmin/
bpm4dm1n/
pemkoadmin/
pemko/
login-page/
login-2/
eklinik
bpm4dm1n/
4dminweb/
loginadmin/
jp/login/
paneladmin/
pmb/
gapura/
e_office/
b_office/
log/
login1/
direkturweb/
pmb/index.php
index.php/loginpmb/
bppd/
4dm1n/
4dm1n1stras1/
member/
ketua/
guru/
bpm4dm1n/
k0dim/
adminer/
pemerintah/
dinas/
rumah/
admbkdm/login.php
admin@web/
admin@web/index.php
administrasi/index.php
login_area/index.php
masterweb/
cp.php
admin/cp.php
login/cp.php
rahasia/
rahasia/login.php
adminpusdatin/
admin/masuk
adm4dep/
adminjdih/
adminpengada/
paneladminweb/
portaldata/
portal/
sakti/
xadmin/
trackingadmin/
l0g1n/
themeadmin/
admins/
tempatlogin/
robots2.txt
l0gin/
main/login.php
auth/login.php
newsadmin/
manage/login.php
terminal/
admincp/login.php
admin2017/
admin2018/
admin2019/
halamanmasuk/
halamanlogin/
admcp/
moderatorcp/
redaktur/admin/login/
docs/admin/login/
staff/admin/login
adm1nw3b/
admin/adm
acces/
admin-jdih/
db/login.php
db/admin/login.php
panel/bp_login/
admindata/
akulogin/
admbkdm/
pmb/admin/
trackingadmin/
khusus/
khusu/admin/
panels/
login/ketua/
backend/
secure/login/
v2/administrator/
kelolaweb/
superadminlogin/
login/superadmin/
delegasi/
upload.php
masterweb/index.php
webadmin/index.php
v2/
admin-web/
old/
dulu/
old/adminweb/
webadmin/
superuser/
redakturweb/
simpeg/
terminal/
monitor/
portal/
portaladmin/
terasadmin/
jdih/
manager/
data/
blusukan/
webmin/
myadmin/
adminkota/
adminkota/login.php
admindesa
admindesa/login.php
leb/
w3bc0ntr0l/
adminkoster/
panel/
pegawai/
staffadmin/
upload.php
counterweb/
ereporting/
web-admin/index.php
index.php/adminweb/
author/adminweb/
author/webadmin/index.php
author/admin/
developer/
guru/index.php
loginguru/
lama/adminweb/
backup/login/
backup/adminweb/
author/
admin.web/
v1/login/
v2/admin/
v2/admin/
adminn/
staff/
atur/
loginpt/
adminpt/

loginpage/
adminarea/
formadmin/
admin/index.php
index.php/login
member/login.php
memberarea/
wp-admin/
wp-login.php
mlebu/index.php
webadmin/index.php
master/
redaktur/
redaktur/index.php
default.php
robots.txt
administrator/
administrator/index.php
masuk/index.php
kamaradmin/index.php
logon/index.php
administrasi/index.php
webmaster/index.php
webmaster/
cek_login.php
operator/
loginpt/
jendral/
boss/
adminpt/
adminsekolah/
kampus/
dosen/
koperadmin/
pengelolaweb/
pengelola/
loginweb/
guru/
adminsd/
adminsmk/
admin123/
123/
admin123/login.php
adminsekolah/
loginsmp/
superadmin/
webadmin/
sisurip/
adminsma/
adminsmp/
adminpanel/
control/
webadmin/login.php
portaladmin/
loginsma/
operator/index.php
logout.php
penulis/
file/
xpanel/
staf/
download/
files/
1admin/
2admin/
web/
loggin/
adm/
c_admin/
c_panel/
controladmin/
control/
Admn/
html/
nimda/
mrnimda/
adminwebupt/
adminsiswa/
adminguru/
korpriadmin/
pemkab/
pemkabadmin/
po-admin/
cms/index.php
index.php/login
adminarea
admin2.html
yonetim.php
yonetim.html
yonetici.php
yonetici.html
ccms/
panitia/
posko/
adminpn/
loginpn/
v2/admin/
v3/login
yonetim.php
yonetim.html
yonetici.php
yonetici.html
ccms/
ccms/login.php
ccms/index.php
login@web/
loginweb/
konten/
dinas/
akademik/
templates/
simaset/
administrator/account.html
administrator/account.php
ccms/login.php
ccms/index.php
maintenance/
webmaster/
adm/
config/
configuration/
kontenweb/
configure/
websvn/
ketua/
panitia/
loginpanitia/
pemerintah/
cybercrime/
adipura/
pintumasuk/
pintu/
tersembunyi/
bapeda/
loggin/
admin/
admin.php
admin.html
admin/cp.php
admin/cp.html
cp.php
cp.html
siakad/
journal/
sia/
fakultas/
pegawai/
petugas/
penjaga/
b_office/
4dminW3B/
config/
akademik/
kelolaweb/
aturweb/
counter/
bpadmin/
suradmin/
basecamp/
padmin/
pengaturan/
setting/
settingweb/
redaksi/
adminweb1/
redaktur1/
masukweb/
redaksiweb/
users/
usr/
user/
loginuser/
logincms/
admincms/
userlogin/
adminkampus/
redaksiweb/adweb/
bismillah/
adweb2_cad/
kuncen/
dasboard/
administrator/
administrator/index.html
administrator/index.php
administrator/login.html
administrator/login.php
administrator/account.html
administrator/account.php
administrator.php
administrator.html
login.php
login.html
modelsearch/login.php
moderator.php
moderator.html
moderator/login.php
moderator/login.html
moderator/admin.php
moderator/admin.html
moderator/
account.php
account.html
controlpanel/
controlpanel.php
controlpanel.html
admincontrol.php
admincontrol.html
adminpanel.php
adminpanel.html
admin1.asp
admin2.asp
yonetim.asp
yonetici.asp
admin/account.asp
admin/index.asp
admin/login.asp
admin/home.asp
admin/controlpanel.asp
admin.asp
admin/cp.asp
cp.asp
system
rahasia/
rahasia/login.php
rahasia/admin.php
rahasia/index.php
dinkesadmin/login.php
adminpmb
adminpmb/index.php
adminpmb/login.php
system/index.php
system/login.php
system/admin.php
administrator/index.asp
administrator/login.asp
administrator/account.asp
administrator.asp
login.asp
modelsearch/login.asp
moderator.asp
moderator/login.asp
moderator/admin.asp
account.asp
controlpanel.asp
admincontrol.asp
adminpanel.asp
fileadmin/
fileadmin.php
fileadmin.asp
fileadmin.html
administration/
administration.php
administration.html
sysadmin.php
sysadmin.html
phpmyadmin/
myadmin/
sysadmin.asp
sysadmin/
ur-admin.asp
ur-admin.php
ur-admin.html
ur-admin/
Server.php
Server.html
Server.asp
Server/
wp-admin/
administr8.php
administr8.html
administr8/
administr8.asp
webadmin/
webadmin.php
webadmin.asp
webadmin.html
administratie/
admins/
admins.php
admins.asp
admins.html
administrivia/
Database_Administration/
WebAdmin/
useradmin/
sysadmins/
admin1/
system-administration/
administrators/
pgadmin/
directadmin/
staradmin/
s_adminwebX/
s_adminweb/
assest/
mini.php/
wso.php
symlink.php
kcfinder/browse.php?type=image
welcome/
dashboard/
ServerAdministrator/
SysAdmin/
administer/
LiveUser_Admin/
sys-admin/
typo3/
panel/
cpanel/
cPanel/
cpanel_file/
platz_login/
rcLogin/
blogindex/
formslogin/
autologin/
support_login/
meta_login/
manuallogin/
simpleLogin/
loginflat/
utility_login/
showlogin/
memlogin/
members/
login-redirect/
sub-login/
wp-login/
login1/
dir-login/
login_db/
xlogin/
smblogin/
customer_login/
UserLogin/
login-us/
acct_login/
admin_area/
bigadmin/
project-admins/
phppgadmin/
pureadmin/
sql-admin/
radmind/
openvpnadmin/
wizmysqladmin/
vadmind/
ezsqliteadmin/
hpwebjetadmin/
newsadmin/
adminpro/
Lotus_Domino_Admin/
bbadmin/
vmailadmin/
Indy_admin/
ccp14admin/
irc-macadmin/
banneradmin/
sshadmin/
phpldapadmin/
macadmin/
administratoraccounts/
admin4_account/
admin4_colon/
radmind-1/
Super-Admin/
AdminTools/
cmsadmin/
SysAdmin2/
globes_admin/
cadmins/
phpSQLiteAdmin/
navSiteAdmin/
server_admin_small/
logo_sysadmin/
server/
database_administration/
power_user/
system_administration/
ss_vms_admin_sm/
adminarea/
bb-admin/
adminLogin/
panel-administracion/
instadmin/
memberadmin/
administratorlogin/
admin/admin.php
admin_area/admin.php
admin_area/login.php
siteadmin/login.php
siteadmin/index.php
siteadmin/login.html
admin/admin.html
admin_area/index.php
bb-admin/index.php
bb-admin/login.php
bb-admin/admin.php
admin_area/login.html
admin_area/index.html
admincp/index.asp
admincp/login.asp
admincp/index.html
webadmin/index.html
webadmin/admin.html
webadmin/login.html
admin/admin_login.html
admin_login.html
panel-administracion/login.html
nsw/admin/login.php
webadmin/login.php
admin/admin_login.php
admin_login.php
admin_area/admin.html
pages/admin/admin-login.php
admin/admin-login.php
admin-login.php
bb-admin/index.html
bb-admin/login.html
bb-admin/admin.html
admin/home.html
pages/admin/admin-login.html
admin/admin-login.html
admin-login.html
admin/adminLogin.html
adminLogin.html
home.html
rcjakar/admin/login.php
adminarea/index.html
adminarea/admin.html
webadmin/index.php
webadmin/admin.php
user.html
modelsearch/login.html
adminarea/login.html
panel-administracion/index.html
panel-administracion/admin.html
modelsearch/index.html
modelsearch/admin.html
admincontrol/login.html
adm/index.html
adm.html
user.php
panel-administracion/login.php
wp-login.php
adminLogin.php
admin/adminLogin.php
home.php
adminarea/index.php
adminarea/admin.php
adminarea/login.php
panel-administracion/index.php
panel-administracion/admin.php
modelsearch/index.php
modelsearch/admin.php
admincontrol/login.php
admloginuser.php
admin2/login.php
admin2/index.php
adm/index.php
adm.php
register.html
aturdata/
4dm1n/
mini.php
boostrap/filemanager/
sca.php
lnx.php
makassar.php
mini.phtml
uploader.phtml
404.phtml
up.php.pjpeg
x.php
what.php
ri1z.php
indoXploit.php
indo.php
d7.php
uploader.php
system.php
demo.php
admin/file/file_post/str_fungsi.php
admin/plupload/examples/upload.php
assets/plugins/plupload/examples/upload.php
admin/assets/plupload/examples/upload.php
file/file_post/str_fungsi.php
assets/global/plugins/jquery-file-upload/server/php/
assets/plugins/jquery-file-upload/server/php/
adminpanel/
panel/
panel/login.php
login/panel/
admin/panel/
rahasia/login/
member/daftar.php
alumni/
4dm1nw3b/
admin@sekolah/
admin@kpu/
kpuadmin/
robots.txt.dist
upload.php
indoXploit.php
shell.php
sedot/
rahasia/
aplikasi/
dashboard/login.php
dashboard/admin.php
loginadmin/
backoffice/
adminpt
user/
userpie/
adminkpud/
adminkpu/
themes/
loginkpud/
loginkpud/
loginweb/
indoxploit.php
perdata/login.php
affiliate.php
adm_auth.php
maklo.php
admin/admin.php
login/login/admin
login/login/
cms/login.php
eksekutif/login.php
cms/
simple/login
daktaken.php
public/login.php
subd0m41n/login.php
subd0m41n/
4dm1n15tr4t0r/
adminwebbgsg/
adminpage/
adminadabug/
adminadabugdisini/
kembug/
bugmkx/
4dm1n/
dinas/administrator/
login/4dm1n/
admin/administrator/
admin/admin/
dinas/login.php
findIT/
dinkes/
dinkes/login/
dinkes/login.php
v1/login php
v1/admin/
v2/admin/
v2/login.php
kontributor/
hukum/
hukum/admin/
superman.php
member.php
home/admin
do_login.php
bo-login
bo_login.php/
index.php/admin
admiiin.php
masuk/adm
website_login/
dashboard/admin
dashboard.php
dashboard_adm
admin123/login.php
logout1/
logout/
pengelola/login
manageradm/
logout.asp
manager/adm
pengelola/web
auth/panel
logout/index.php
logout/login.php
controladm/
logout/admin.php
adminweb_setting/
usuarios/
usuario/
panel-administracion/
instadmin/
memberadmin/
administratorlogin/
adm/
admin/account
admin/index.brf
admin/login.brf
admin/admin.brf
admin/account.brf
admin_area/admin.brf
admin_area/login.brf
siteadmin/login.brf
siteadmin/index.brf
siteadmin/login.html
admin/account.html
admin/index.html
admin/login.html
admin/admin.html
admin_area/index.brf
bb-admin/index.brf
bb-admin/login.brf
hb-admin/admin.brf
admin/home.brf
admin_area/login.html
admin_area/index.html
admin/controlpanel.brf
admin.brf
admincp/index.asp
admincp/login.asp
admincp/index.html
admin/account.html
adminpanel.html
sebadmin.html
webadmin/index.html
webadmin/admin.html
webadmin/login.html
admin/admin_login.html
admin_login.html
panel-administracion/login.html
admin/cp.brf
cp.brf
administrator/index.brf
ladministrator/login.brf
nsw/admin/login.brf
webadmin/login.brfbrf
admin/admin_login.brf
admin_login.brf
administrator/account.brf
administrator.brf
acceso.brf
admin_area/admin.html
pages/admin/admin-login.brf
admin/admin-login.brf
admin-login.brf
bb-admin/index.html
bb-admin/login.html
bb-admin/admin.html
admin/home.html
login.brf
modelsearch/login.brf
moderator.brf
moderator/login.brf
moderator/admin.brf
account.brf
pages/admin/admin-login.html
admin/admin-login.html
admin-login.html
controlpanel.brf
admincontrol.brf
admin/adminLogin.ht
adminLogin.html
admin/adminLogin.html
home.html
rcjakar/admin/login.brf
adminarea/index.html
adminarea/admin.html
webadmin.brf
webadmin/index.brf
webadmin/admin.brf
admin/controlpanel.ht
admin.html
admin/cp.html
cp.html
adminpanel.brf
moderator.html
administrator/index.html
administrator/login.html
user.html
administrator/account.html
administrator.ht
login.html
modelsearch/login.html
moderator/login.html
adminarea/login.html
panel-administracion/index.html
panel-administracion/admin.html
modelsearch/index.html
modelsearch/admin.html
admincontrol/login.html
adm/index.html
adm.html
moderator/admin.html
user.brf
account.html
controlpanel.html
admincontrol.html
panel-administracion/login.brf
wp-login.brf
adminLogin.brf
admin/adminLogin.brf
gome.brf
admin.brf
adminarea/index.brf
adminarea/admin.brf
adminarea/login.brf
panel-administracion/index.brf
panel-administracion/admin.brf
modelsearch/index.brf
modelsearch/admin.brf
admincontrol/login.brf
adm/admloginuser.brf
admloginuser.brf
admin2.brf
admin2/login.brf
admin2/index.brf
usuarios/login.brf
adm/index.brf
adm.brf
affiliate.brf
adm_auth.brf
memberadmin.brf
administratorlogin.brf
admin_area/
panel-administracion/
instadmin/
memberadmin/
administratorlogin/
adm/
admin/account.php
admin/index.php
admin/login.php
admin/admin.php
admin/account.php
admin_area/admin.php
admin_area/login.php
siteadmin/login.php
siteadmin/index.php
siteadmin/login.html
admin/account.html
admin/index.html
admin/login.html
admin/admin.html
admin_area/index.php
bb-admin/index.php
bb-admin/login.php
bb-admin/admin.php
admin/home.php
admin_area/login.html
admin_area/index.html
admin/controlpanel.php
admin.php
admincp/index.asp
admincp/login.asp
admincp/index.html
admin/account.html
adminpanel.html
webadmin.html
webadmin/index.html
webadmin/admin.html
webadmin/login.html
admin/admin_login.html
admin_login.html
panel-administracion/login.html
admin/cp.php
cp.php
administrator/index.php
administrator/login.php
nsw/admin/login.php
webadmin/login.php
admin/admin_login.php
admin_login.php
administrator/account.php
administrator.php
admin_area/admin.html
pages/admin/admin-login.php
admin/admin-login.php
admin-login.php
bb-admin/index.html
bb-admin/login.html
acceso.php
bb-admin/admin.html
admin/home.html
login.php
modelsearch/login.php
moderator.php
moderator/login.php
moderator/admin.php
account.php
pages/admin/admin-login.html
admin/admin-login.html
admin-login.html
controlpanel.php
admincontrol.php
admin/adminLogin.html
adminLogin.html
admin/adminLogin.html
home.html
rcjakar/admin/login.php
adminarea/index.html
adminarea/admin.html
webadmin.php
webadmin/index.php
webadmin/admin.php
admin/controlpanel.html
admin.html
admin/cp.html
cp.html
adminpanel.php
moderator.html
administrator/login.html
user.html
administrator/account.html
administrator.html
login.html
modelsearch/login.html
moderator/login.html
adminarea/login.html
panel-administracion/index.html
panel-administracion/admin.html
modelsearch/index.html
modelsearch/admin.html
admincontrol/login.html
adm/index.html
adm.html
moderator/admin.html
user.phpl
account.html
controlpanel.html
admincontrol.html
panel-administracion/login.php
wp-login.php
adminLogin.php
admin/adminLogin.php
home.php
admin.php
adminarea/index.php
adminarea/admin.php
adminarea/login.php
panel-administracion/index.php
panel-administracion/admin.php
modelsearch/index.php
modelsearch/admin.php
admincontrol/login.php
adm/admloginuser.php
admloginuser.php
admin2.php
admin2/login.php
admin2/index.php
usuarios/login.php
adm/index.php
adm.php
affiliate.php
adm_auth.php
memberadmin.php
administratorlogin.php
admin
yonetim.php
yonetim.html
yonetici.php
yonetici.html
ccms/
ccms/login.php
ccms/index.php
maintenance/
webmaster/
adm/
configuration/
configure/
websvn/
admin/
admin/account.php
admin/account.html
yonetim.asp
yonetici.asp
modelsearch/login.asp
fileadmin/
fileadmin.php
fileadmin.asp
fileadmin.html
administration/
administration.php
administration.html
sysadmin.php
sysadmin.html
phpmyadmin/
myadmin/
sysadmin.asp
sysadmin/
ur-admin.asp
ur-admin.php
ur-admin.html
ur-admin/
Server.php
Server.html
Server.asp
Server/
administrivia/
Database_Administration/
WebAdmin/
pgadmin/
directadmin/
staradmin/
ServerAdministrator/
SysAdmin/
administer/
LiveUser_Admin/
sys-admin/
typo3/
cpanel_file/
platz_login/
rcLogin/
blogindex/
formslogin/
autologin/
support_login/
meta_login/
manuallogin/
simpleLogin/
loginflat/
utility_login/
showlogin/
memlogin/
members/
login-redirect/
sub-login/
login1/
dir-login/
login_db/
xlogin/
smblogin/
customer_login/
UserLogin/
login-us/
acct_login/
admin_area/
bigadmin/
project-admins/
phppgadmin/
pureadmin/
sql-admin/
radmind/
openvpnadmin/
wizmysqladmin/
vadmind/
ezsqliteadmin/
hpwebjetadmin/
newsadmin/
adminpro/
Lotus_Domino_Admin/
bbadmin/
vmailadmin/
Indy_admin/
ccp14admin/
irc-macadmin/
banneradmin/
sshadmin/
phpldapadmin/
macadmin/
administratoraccounts/
admin4_account/
admin4_colon/
radmind-1/
Super-Admin/
AdminTools/
cmsadmin/
SysAdmin2/
globes_admin/
cadmins/
phpSQLiteAdmin/
navSiteAdmin/
server_admin_small/
logo_sysadmin/
server/
database_administration/
power_user/
system_administration/
ss_vms_admin_sm/
adminarea/
bb-admin/
adminLogin/
panel-administracion/
instadmin/
memberadmin/
administratorlogin/
admin/admin.php
admin_area/admin.php
admin_area/login.php
siteadmin/login.php
siteadmin/index.php
siteadmin/login.html
admin/admin.html
admin_area/index.php
bb-admin/index.php
bb-admin/login.php
bb-admin/admin.php
admin_area/login.html
admin_area/index.html
admincp/index.asp
admincp/login.asp
admincp/index.html
webadmin/index.html
webadmin/admin.html
webadmin/login.html
admin/admin_login.html
admin_login.html
panel-administracion/login.html
nsw/admin/login.php
webadmin/login.php
admin/admin_login.php
admin_login.php
admin_area/admin.html
pages/admin/admin-login.php
admin/admin-login.php
admin-login.php
bb-admin/index.html
bb-admin/login.html
bb-admin/admin.html
admin/home.html
pages/admin/admin-login.html
admin/admin-login.html
admin-login.html
admin/adminLogin.html
adminLogin.html
rcjakar/admin/login.php
adminarea/index.html
adminarea/admin.html
webadmin/index.php
webadmin/admin.php
user.html
modelsearch/login.html
adminarea/login.html
panel-administracion/index.html
panel-administracion/admin.html
modelsearch/index.html
modelsearch/admin.html
admincontrol/login.html
adm/index.html
adm.html
user.php
panel-administracion/login.php
wp-login.php
adminLogin.php
admin/adminLogin.php
home.php
adminarea/index.php
adminarea/admin.php
adminarea/login.php
panel-administracion/index.php
panel-administracion/admin.php
modelsearch/index.php
modelsearch/admin.php
admincontrol/login.php
adm/admloginuser.php
admloginuser.php
admin2/login.php
admin2/index.php
adm/index.php
adm.php
affiliate.php
adm_auth.php
memberadmin.php
administratorlogin.php
admin/admin.asp
admin_area/admin.asp
admin_area/login.asp
admin_area/index.asp
bb-admin/index.asp
bb-admin/login.asp
bb-admin/admin.asp
pages/admin/admin-login.asp
admin/admin-login.asp
admin-login.asp
user.asp
webadmin/index.asp
webadmin/admin.asp
webadmin/login.asp
admin/admin_login.asp
admin_login.asp
panel-administracion/login.asp
adminLogin.asp
admin/adminLogin.asp
home.asp
adminarea/index.asp
adminarea/admin.asp
adminarea/login.asp
panel-administracion/index.asp
panel-administracion/admin.asp
modelsearch/index.asp
modelsearch/admin.asp
admincontrol/login.asp
adm/admloginuser.asp
admloginuser.asp
admin2/login.asp
admin2/index.asp
adm/index.asp
adm.asp
affiliate.asp
adm_auth.asp
memberadmin.asp
administratorlogin.asp
siteadmin/login.asp
webmaster
siteadmin/index.asp
ADMIN/
ADMIN/login.php
panelc/
register
admin/admin-login.asp
admin-login.asp
user.asp
webadmin/index.asp
webadmin/admin.asp
webadmin/login.asp
admin/admin_login.asp
admin_login.asp
panel-administracion/login.asp
adminLogin.asp
admin/adminLogin.asp
home.asp
adminarea/index.asp
adminarea/admin.asp
adminarea/login.asp
panel-administracion/index.asp
panel-administracion/admin.asp
modelsearch/index.asp
modelsearch/admin.asp
admincontrol/login.asp
adm/admloginuser.asp
admloginuser.asp
admin2/login.asp
admin2/index.asp
adm/index.asp
adm.asp
affiliate.asp
adm_auth.asp
memberadmin.asp
administratorlogin.asp
siteadmin/login.asp
siteadmin/index.asp
ADMIN/
paneldecontrol/
login/
cms/
admon/
ADMON/
administrador/
ADMIN/login.php
panelc/
ADMIN/login.html";
function template() {
echo '
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta **********="Content-Type" *********"text/html; charset=utf-8" />
<title>Nyari admin</title>

<style type="text/css">

h1.technique-two {
        width: 795px; height: 120px;
        background: url(http://x0rg.org/styles/blackbox_red/imageset/site_logo.gif) no-repeat top center;
        margin: 0 auto;
}
body{
    background: #070707;
    margin: 0;
    padding: 0;
    padding-top: 10px;
    color: red;
    font-family: Sancreek;
    font-size: 13px;
}
a{
    color: #FFF;
    text-decoration: none;
    font-weight: bold;
}
.wrapper{
    width: 1000px;
    margin: 0 auto;
}
.tube{
    padding: 10px;
}
.red{
    width: 998px;
    border: 2px dashed grey;
    background: #191919;
    color: red;
}
.red input{
    background: transparent;
    border: 2px inset grey;
   height: 30px;
   width: 200px
    font-color: red;
    color: red;
}
.blue{
    float: left;
    width: 1000px;
    border: 2px dashed grey;
    background: #191919;
    color: skyblue;
}
.green{
    float: left;
    width: 1000px;
    border: 2px dashed grey ;
    background: #191919;
    color: red;
}
</style>
<script type="text/javascript">
<!--
function insertcode($text, $place, $replace)
{
    var $this = $text;
    var logbox = document.getElementById($place);
    if($replace == 0)
        document.getElementById($place).innerHTML = logbox.innerHTML+$this;
    else
        document.getElementById($place).innerHTML = $this;
//document.getElementById("helpbox").innerHTML = $this;
}
-->
</script>
</head>
<body>
<br />
<p align="center">
<font style="text-align:center;color:skyblue;font-family:Cardo;font-size:50px; text-shadow:0px 0px 5px blue;">=>habang login<=</font>
</p>
<h1 class="technique-two">
       


</h1>

<div class="wrapper">
<div class="red">
<div class="tube">
<form action="" method="post" name="xploit_form">
URL:<br /><input type="text" name="xploit_url" value="'.$_POST['xploit_url'].'" style="width: 50%;" />
<input type="submit" name="xploit_submit" value="hajar" align="right" />
<input type="hidden" name="xploit_404string" value="'.$_POST['xploit_404string'].'" style="width: 50%;" /><br />
<span style="float: right;"></span>
</form>
<br />
</div> <!-- /tube -->
</div> <!-- /red -->
<div class="green">
<div class="tube" id="rightcol">
Verificat: <span id="verified">0</span> / <span id="total">0</span><br />
kimcil yang di temukan:<br />
</div> <!-- /tube -->
</div> <!-- /green -->
<br clear="all" /><br />
<div class="red">
<div class="tube" id="logbox">
tempet login by akbar <br /><br />
</div> <!-- /tube -->
</div> <!-- /red -->
</div> <!-- /wrapper -->
<br clear="all">';
}
function show($msg, $br=1, $stop=0, $place='logbox', $replace=0) {
    if($br == 1) $msg .= "<br />";
    echo "<script type=\"text/javascript\">insertcode('".$msg."', '".$place."', '".$replace."');</script>";
    if($stop == 1) exit;
    @flush();@ob_flush();
}
function check($x, $front=0) {
    global $_POST,$site,$false;
    if($front == 0) $t = $site.$x;
    else $t = 'http://'.$x.'.'.$site.'/';
    $headers = get_headers($t);
    if (!eregi('200', $headers[0])) return 0;
    $data = @file_get_contents($t);
    if($_POST['xploit_404string'] == "") if($data == $false) return 0;
    if($_POST['xploit_404string'] != "") if(strpos($data, $_POST['xploit_404string'])) return 0;
    return 1;
}
   
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
template();
if(!isset($_POST['xploit_url'])) die;
if($_POST['xploit_url'] == '') die;
$site = $_POST['xploit_url'];
if ($site[strlen($site)-1] != "/") $site .= "/";
if($_POST['xploit_404string'] == "") $false = @file_get_contents($site."d65897f5380a21a42db94b3927b823d56ee1099a-this_can-t_exist.html");
$list['end'] = str_replace("\r", "", $list['end']);
$list['front'] = str_replace("\r", "", $list['front']);
$pathes = explode("\n", $list['end']);
$frontpathes = explode("\n", $list['front']);
show(count($pathes)+count($frontpathes), 1, 0, 'total', 1);
$verificate = 0;
foreach($pathes as $path) {
    show('Checking '.$site.$path.' : ', 0, 0, 'logbox', 0);
    $verificate++; show($verificate, 0, 0, 'verified', 1);
    if(check($path) == 0) show('not found', 1, 0, 'logbox', 0);
    else{
        show('<span style="color: #00FF00;"><strong>found</strong></span>', 1, 0, 'logbox', 0);
        show('<a href="'.$site.$path.'">'.$site.$path.'</a>', 1, 0, 'rightcol', 0);
    }
}
preg_match("/\/\/(.*?)\//i", $site, $xx); $site = $xx[1];
if(substr($site, 0, 3) == "www") $site = substr($site, 4);
foreach($frontpathes as $frontpath) {
    show('Checking http://'.$frontpath.'.'.$site.'/ : ', 0, 0, 'logbox', 0);
    $verificate++; show($verificate, 0, 0, 'verified', 1);
    if(check($frontpath, 1) == 0) show('not found', 1, 0, 'logbox', 0);
    else{
        show('<span style="color: #00FF00;"><strong>found</strong></span>', 1, 0, 'logbox', 0);
        show('<a href="http://'.$frontpath.'.'.$site.'/">'.$frontpath.'.'.$site.'</a>', 1, 0, 'rightcol', 0);
    }
   
}
?>
